
export type FinancialItem = {
    id:number,
    name:string;
    image:string;
}

export const financialList : FinancialItem [] = [
    {   
        id:1,
        name:"atb",
        image:"./financial_logos/atb.png"
    },
    {
        id:2,
        name:"cibc",
        image:"./financial_logos/cibc.png"
    },
    {
        id:3,
        name:"desjardin",
        image:"./financial_logos/desjardin.png"
    },
    {
        id:4,
        name:"hsbc",
        image:"./financial_logos/hsbc.png"
    },
    {
        id:5,
        name:"manulife",
        image:"./financial_logos/manulife.png"
    },
    {
        id:6,
        name:"meridian",
        image:"./financial_logos/meridian.png"
    },
    {
        id:7,
        name:"paypal",
        image:"./financial_logos/paypal.png"
    },
    {
        id:8,
        name:"scotia",
        image:"./financial_logos/scotia.png"
    },
    {
        id:9,
        name:"tangerine",
        image:"./financial_logos/tangerine.png"
    },
    {
        id:10,
        name:"tdbank",
        image:"./financial_logos/tdbank.png"
    },
] 